# Copyright (c) 2023 The Kroger Co. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: 'Check for Sign-off'
description: 'Checks for all necessary sign-off before merging'
inputs:
  branch-name:
    description: 'The name of the branch you want to get sign-off.json from'
    required: false
    default: 'main'
  file-name:
    description: 'The name of the file that has the list of users'
    required: false
    default: 'sign-off'
  github-token:
    description: 'Token for accessing repo'
    required: true
  label:
    description: 'The label that needs to be removed for the PR to be accepted'
    required: false
    default: 'needs-qa'
  path:
    description: 'The path to the list of approvers'
    required: false
    defaults: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
